name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install .[dev]
      - name: Lint (flake8)
        run: flake8
      - name: Format check (black)
        run: black --check .
      - name: Import order (isort)
        run: isort --check-only .
      - name: Type check (mypy)
        run: mypy src
      - name: Tests
        run: pytest -q
